apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: demo-ui-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: demo-ui
    minReplicas: 2
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
